# <span style="color:red"> Lecture 22a: Recoding Variables </span>

<font size = "4">

"Recoding" variables means changing/re-expressing existing variables into a new set of values that may be more useful for data analysis.

Examples:

- A variable called "age" consists of integers beginning at 0 (how old the person is in terms of years). We can transform this into a categorical variable with the values "child", "teenager", "young adult", "adult", "senior"

- A variable called "submission_time" records the time that a student submitted an assignment to Gradescope. We can transform this into a categorical variable with the values "on time" and "late"

- A variable called "candidate_preference" is taken from a survey of people asking which of two presidential candidates they will vote for. This is a categorical variable with the values "Candidate A", "Candidate B", "Don't Know", "Refused", "Blank", "Other Candidate". This is recoded to another categorical variable with only 3 values "Candidate A", "Candidate B", and "Neither".

- We convert a variable "height" measured in inches, to a corresponding variable measuring height in centimeters.

- A variable called "lat" consists of floating point numbers consisting of a geographical coordinate measuring the distance north or south of the Equator. We change this into a categorical variable with the values "north" or "south".

<font size = "4">

We'll perform this last one in **3 different ways** using the circuits data we cleaned last time. In each way, we will consider as "south" those circuits with $-90 < \textrm{lat} \leq 0$ and "north" as circuits with $0 < \textrm{lat} \leq 90$

In [1]:
import pandas as pd

circuits = pd.read_csv("f1_clean_data/circuits_final.csv")

circuits.head()

,circuitID,circuitRef,name,location,country,lat,lng,alt,url,alt_numeric
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10.0,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,10.0
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18.0,http://en.wikipedia.org/wiki/Sepang_Internatio...,18.0
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7.0,http://en.wikipedia.org/wiki/Bahrain_Internati...,7.0
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109.0,http://en.wikipedia.org/wiki/Circuit_de_Barcel...,109.0
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130.0,http://en.wikipedia.org/wiki/Istanbul_Park,130.0

<font size = "4">

Here we do it manually with a for loop and an if/else statement:

In [2]:
nrows, ncols = circuits.shape 

col_no = 5 # column 5 is "lat"
hemisphere = []

for k in range(nrows):
    lat_val = circuits.iloc[k, col_no]
    if lat_val <= 0:
        hemisphere.append("South")
    else:
        hemisphere.append("North")

# could overwrite "lat", but is almost always better to keep the original variable
circuits["hemisphere"] = hemisphere

# Note: I made sure the data in this column didn't need to be cleaned first!!
circuits.head()

,circuitID,circuitRef,name,location,country,lat,lng,alt,url,alt_numeric,hemisphere
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10.0,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,10.0,South
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18.0,http://en.wikipedia.org/wiki/Sepang_Internatio...,18.0,North
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7.0,http://en.wikipedia.org/wiki/Bahrain_Internati...,7.0,North
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109.0,http://en.wikipedia.org/wiki/Circuit_de_Barcel...,109.0,North
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130.0,http://en.wikipedia.org/wiki/Istanbul_Park,130.0,North

<font size = "4">

Let's drop the "hemisphere" column to verify that the next approach we try actually works

In [3]:
circuits.drop(columns = "hemisphere",inplace = True)
circuits.head()

,circuitID,circuitRef,name,location,country,lat,lng,alt,url,alt_numeric
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10.0,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,10.0
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18.0,http://en.wikipedia.org/wiki/Sepang_Internatio...,18.0
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7.0,http://en.wikipedia.org/wiki/Bahrain_Internati...,7.0
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109.0,http://en.wikipedia.org/wiki/Circuit_de_Barcel...,109.0
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130.0,http://en.wikipedia.org/wiki/Istanbul_Park,130.0

<font size = "4">

In the next cell, I *attempt* to use `.apply` to recode the data. 

**What error did I make and how should I fix it?**

In [4]:
def check_hemisphere(lat):
    if lat <= 0: # this line used to say "lat_val <= 0"
        return "South" 
    else:
        return "North"

circuits["hemisphere"] = circuits["lat"].apply(check_hemisphere)

circuits.head()

,circuitID,circuitRef,name,location,country,lat,lng,alt,url,alt_numeric,hemisphere
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10.0,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,10.0,South
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18.0,http://en.wikipedia.org/wiki/Sepang_Internatio...,18.0,North
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7.0,http://en.wikipedia.org/wiki/Bahrain_Internati...,7.0,North
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109.0,http://en.wikipedia.org/wiki/Circuit_de_Barcel...,109.0,North
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130.0,http://en.wikipedia.org/wiki/Istanbul_Park,130.0,North

In [5]:
# dropping the "hemisphere" column again:
circuits.drop(columns = "hemisphere",inplace = True)
circuits.head()

,circuitID,circuitRef,name,location,country,lat,lng,alt,url,alt_numeric
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10.0,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,10.0
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18.0,http://en.wikipedia.org/wiki/Sepang_Internatio...,18.0
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7.0,http://en.wikipedia.org/wiki/Bahrain_Internati...,7.0
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109.0,http://en.wikipedia.org/wiki/Circuit_de_Barcel...,109.0
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130.0,http://en.wikipedia.org/wiki/Istanbul_Park,130.0

<font size = "4">

Finally, I use the function `pd.cut` which is used to segment data into "intervals" or "bins".

Remember, we are recoding the latitute variable based on the following criteria:

- If $-90 < \textrm{lat} \leq 0$, the circuit is labeled "south"

- If $0 < \textrm{lat} \leq 90$, the circuit is labeled "north"

In [6]:
lat_bins = [-90, 0, 90]

lat_labels = ["South", "North"]
circuits["hemisphere"] = pd.cut(circuits["lat"], 
                                bins = lat_bins,
                                right = True,
                                labels = lat_labels)

# The "right" command indicates that the right endpoint of each interval
# is *inclusive*, i.e. "less than or equal to"


circuits.head()

,circuitID,circuitRef,name,location,country,lat,lng,alt,url,alt_numeric,hemisphere
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10.0,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,10.0,South
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18.0,http://en.wikipedia.org/wiki/Sepang_Internatio...,18.0,North
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7.0,http://en.wikipedia.org/wiki/Bahrain_Internati...,7.0,North
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109.0,http://en.wikipedia.org/wiki/Circuit_de_Barcel...,109.0,North
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130.0,http://en.wikipedia.org/wiki/Istanbul_Park,130.0,North

<font size = "4">

Alternatively, we can implement it more robustly by recoding the latitude variable by:

- If $-\infty < \textrm{lat} \leq 0$, the circuit is labeled "south"

- If $0 < \textrm{lat} \leq \infty$, the circuit is labeled "north"

(Important in the unlikely event an F1 racetrack is ever built directly at the South Pole)

In [ ]:
import numpy as np

lat_bins = [-np.inf, 0, np.inf]

lat_labels = ["South", "North"]
circuits["hemisphere"] = pd.cut(circuits["lat"], 
                                bins = lat_bins,
                                right = True,
                                labels = lat_labels)


# Note: Since we set lat_bins = [-np.inf, 0, np.inf]
# then intervals are "Less than or equal to 0" and "Above 0"

circuits.head()

,circuitID,circuitRef,name,location,country,lat,lng,alt,url,alt_numeric,hemisphere
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10.0,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,10.0,South
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18.0,http://en.wikipedia.org/wiki/Sepang_Internatio...,18.0,North
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7.0,http://en.wikipedia.org/wiki/Bahrain_Internati...,7.0,North
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109.0,http://en.wikipedia.org/wiki/Circuit_de_Barcel...,109.0,North
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130.0,http://en.wikipedia.org/wiki/Istanbul_Park,130.0,North

<font size = "4">

**Exercise:** Recode the altitude variable into a categorial variable with the values

- "Low altitude" if $\textrm{altitude} \leq 45$
- "Medium altitude" if $45 < \textrm{altitude} \leq 145$
- "High altitude" if $145 < \textrm{altitude}$

Try to write the code without guessing/looking at the minimum and maximum value of altitude in the dataset

In [ ]:

alt_bins = [-np.inf, 45, 145, np.inf]

alt_labels = ["Low altitude", "Medium altitude", "High altitude"]
circuits["alt_type"] = pd.cut(circuits["alt"], 
                                bins = alt_bins,
                                right = True,
                                labels = alt_labels)



circuits.head()

,circuitID,circuitRef,name,location,country,lat,lng,alt,url,alt_numeric,hemisphere,alt_type
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10.0,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,10.0,South,Low altitude
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18.0,http://en.wikipedia.org/wiki/Sepang_Internatio...,18.0,North,Low altitude
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7.0,http://en.wikipedia.org/wiki/Bahrain_Internati...,7.0,North,Low altitude
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109.0,http://en.wikipedia.org/wiki/Circuit_de_Barcel...,109.0,North,Medium altitude
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130.0,http://en.wikipedia.org/wiki/Istanbul_Park,130.0,North,Medium altitude

<font size = "4">

**Exercise:** What happens if you use the ``Pandas`` function ``.cut`` if the bins you provide don't capture all the data in the column? What happens if there are missing values in the column? Test it out by recoding the altitude variable into a categorical variable with the values:

- "Group A" if $0 < \textrm{altitude} \leq 120$
- "Group B" if $120 < \textrm{altitude} \leq 400$
- "Group C" if $400 < \textrm{altitude} \leq 800$

In [ ]:
alt_bins = [0, 120, 400, 800]

alt_labels = ["Group A", "Group B", "Group C"]
circuits["alt_group"] = pd.cut(circuits["alt"], 
                                bins = alt_bins,
                                right = True,
                                labels = alt_labels)


circuits.head()

print(circuits.loc[74, "alt"])
print("When the altitude value is missing, pd.cut assigns:",
      circuits.loc[74, "alt_group"])
print()
print(circuits.loc[70, "alt"])
print("When the altitude is below sea level (negative), pd.cut assigns:",
      circuits.loc[70, "alt_group"])
print()
print(circuits.loc[28, "alt"])
print("When the altitude is higher than 800, pd.cut assigns:",
      circuits.loc[28, "alt_group"])

nan
When the altitude value is missing, pd.cut assigns: nan

-7.0
When the altitude is below sea level (negative), pd.cut assigns: nan

1460.0
When the altitude is higher than 800, pd.cut assigns: nan