# <span style="color:red"> DATASCI 151 - Practice Quiz #5 </span>

<font size = "4" >
This quiz is open book 

<br>

- You <span style="color:red"> CAN </span> use all material from the course repo

- You should <span style="color:red"> NOT </span> use other resources outside the course repo.

- You should <span style="color:red"> NOT </span> collaborate with other students

- Use of LLMs or any AI tools is <span style="color:red"> NOT ALLOWED </span>

- To get full credit, the code should work as intended. But try to attempt every problem - you can still receive partial credit.

<br>

Print the following string:

"I will abide by Emory's code of conduct"

In [1]:
print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

In [2]:
# import necessary libraries here
import pandas as pd
import numpy as np

<font size = "4">

**Q1** Recode a numeric column

<font size = "3">

- Read in the file "movies.csv" from the `quiz_data` folder, saving it as a DataFrame.

- Recode the "year" variable to create a new variable called "time_period" with the following categories.

$\qquad$ ``` ["1941-1967","1968-2003","2004-onwards"] ```

- You must use the `pd.cut` function to recode this variable.

- Print the DataFrame to the screen to check your answers

In [3]:
# SOLUTION 1
df = pd.read_csv("quiz_data/movies.csv")

year_bins = [1940, 1967, 2003, np.inf]
year_labels = ["1941-1967", "1968-2003", "2004-onwards"]


df["time_period"] = pd.cut(x = df["year"], 
                bins=year_bins, 
                labels = year_labels)

##### Check that all movies were recoded correctly
display(df.sort_values(by = "year"))

,title,country,runtime(minutes),year,imdb_score,time_period
1,Citizen Kane,American,119,1941,8.2,1941-1967
7,The Umbrellas of Cherbourg,France,91,1964,7.8,1941-1967
6,La Chinoise,France,96,1967,6.9,1941-1967
8,House,Japan,88,1977,7.2,1968-2003
9,Suspiria,Italy,98,1977,7.3,1968-2003
10,Blue Velvet,American,120,1986,7.7,1968-2003
5,A Tale of Two Sisters,Korean,115,2003,7.1,1968-2003
4,Shutter,Thailand,97,2004,7.0,2004-onwards
2,Revenge,France,108,2017,6.4,2004-onwards
3,Okja,Korean,120,2017,7.3,2004-onwards
0,Past Lives,American,106,2023,7.8,2004-onwards

In [ ]:
# SOLUTION 2
df = pd.read_csv("quiz_data/movies.csv")

year_bins = [1941, 1968, 2004, np.inf]
year_labels = ["1941-1967", "1968-2003", "2004-onwards"]


df["time_period"] = pd.cut(x = df["year"], 
                bins=year_bins, 
                labels = year_labels,
                right = False)

##### Check that all movies were recoded correctly
display(df.sort_values(by = "year"))

,title,country,runtime(minutes),year,imdb_score,time_period
1,Citizen Kane,American,119,1941,8.2,1941-1967
7,The Umbrellas of Cherbourg,France,91,1964,7.8,1941-1967
6,La Chinoise,France,96,1967,6.9,1941-1967
8,House,Japan,88,1977,7.2,1968-2003
9,Suspiria,Italy,98,1977,7.3,1968-2003
10,Blue Velvet,American,120,1986,7.7,1968-2003
5,A Tale of Two Sisters,Korean,115,2003,7.1,1968-2003
4,Shutter,Thailand,97,2004,7.0,2004-onwards
2,Revenge,France,108,2017,6.4,2004-onwards
3,Okja,Korean,120,2017,7.3,2004-onwards
0,Past Lives,American,106,2023,7.8,2004-onwards

<font size = "4">

**Q2** Aggregate and Sort

<font size = "3">

- Continue to use the DataFrame from the previous question.

- Do the following in a **single line of code** using chaining:

    - Group the data by "country"
    
    - Aggregate the following statistics: average runtime, maximum runtime, average IMDB score, minimum IMDB score

    - Sort by average IMDB score in **descending order**

- Print the resulting DataFrame to the screen

**Note:** A "single line of code" can continue on to the next line if you use a backslash or wrap the line within a pair of parentheses.

In [5]:
# SOLUTION
(df.groupby("country").agg(avg_run = ('runtime(minutes)', 'mean'),
                    max_run = ('runtime(minutes)', 'max'),
                    avg_imdb = ('imdb_score', 'mean'),
                    min_imdb = ('imdb_score', 'min')).
                    sort_values(by = "avg_imdb", ascending = False))

             avg_run  max_run  avg_imdb  min_imdb
country
American  115.000000      120  7.900000       7.7
Italy      98.000000       98  7.300000       7.3
Japan      88.000000       88  7.200000       7.2
Korean    117.500000      120  7.200000       7.1
France     98.333333      108  7.033333       6.4
Thailand   97.000000       97  7.000000       7.0

<font size = "4">

**Q3** Subsetting data

<font size = "3">

- Continue to use the DataFrame from the previous question.

- Do the following in a **single line of code** using chaining:

    - Subset the observations for 'country == "France" using ```.query()```

    - Sort the values by year (oldest first)

    - Extract the two oldest movies

In [6]:
df.query("country == 'France'").sort_values(by="year").iloc[:2,:]

,title,country,runtime(minutes),year,imdb_score,time_period
7,The Umbrellas of Cherbourg,France,91,1964,7.8,1941-1967
6,La Chinoise,France,96,1967,6.9,1941-1967

<font size = "4">

**Q4** Aggregate and query

<font size = "3">

- Read in the file "sprint_results.csv" from the `quiz_data` folder, saving it as a DataFrame.

- Do the following in a single line using chaining:

    - Extract the subset with constructorId equal to 51.

    - Aggregate the maximum number of laps and average number of laps for each driver in the subset.

    - Extract the subset of these drivers with maximum # of laps $\geq 20$.

In [7]:
# SOLUTION
df_sprint = pd.read_csv("quiz_data/sprint_results.csv")

(df_sprint.query("constructorId == 51").
 groupby("driverId").
 agg(max_laps = ('laps', 'max'), avg_laps = ('laps', 'mean')).
 query("max_laps >= 20"))

          max_laps   avg_laps
driverId
8               24  20.500000
822             23  22.000000
841             24  19.666667
855             23  11.500000

<font size = "4">

**Q5** Calculate race duration

<font size = "3">

- Read in the file "results_cleaned.csv" from the `quiz_data` folder, saving it as a DataFrame.

- The "milliseconds" column shows the race duration for each result measured in milliseconds. Create a new column called "race_duration_minutes" where we convert the race duration to minutes by dividing each millisecond value by 60,000 (which equals $6 \times 10^4$). Equivalently, you can multiply each millisecond value by $\sout{6 \times 10^{-4}}\ \ \frac{1}{6}\times 10^{-4}$

- Group the data by **both** "raceId" and "constructorId" and calculate the average race duration in minutes for each group.

- Sort the data in descending order and then extract the raceId/constructorId pairs with the 5 slowest average times.

In [8]:
# SOLUTION 1
df_results = pd.read_csv("quiz_data/results_cleaned.csv")

df_results["race_duration_minutes"] = df_results["milliseconds"] / 6e4

gb = df_results.groupby(["raceId", "constructorId"])

gb["race_duration_minutes"].mean().sort_values(ascending=False).head(5) # 5 is default value, could omit that

raceId  constructorId
818     129              251.509000
        107              248.783000
847     15               245.466258
        3                245.410900
        5                245.350783
Name: race_duration_minutes, dtype: float64

In [9]:
# SOLUTION 2
df_results = pd.read_csv("quiz_data/results_cleaned.csv")

df_results["race_duration_minutes"] = df_results["milliseconds"] * (1e-4 / 6)

gb = df_results.groupby(["raceId", "constructorId"])

gb["race_duration_minutes"].mean().sort_values(ascending=False).iloc[:5]

raceId  constructorId
818     129              251.509000
        107              248.783000
847     15               245.466258
        3                245.410900
        5                245.350783
Name: race_duration_minutes, dtype: float64

<font size = "4">

**Q6** Aggregate custom statistic

<font size = "3">

- Continue to use the DataFrame corresponding to the data in "results_cleaned.csv".

- When a driver finishes 1st, 2nd, or 3rd it is known as a "podium finish". Write a function that takes in a Pandas Series and returns the number of entries $\leq 3$.

- Group by "driverId" and then aggregate the following statistics: the average of the "points" column, and the number of podium finishes in the "positionOrder" column - use your custom function for this second statistic.

- Merge the aggregated data back into the original DataFrame.

In [10]:
# SOLUTION 1

df_results = pd.read_csv("quiz_data/results_cleaned.csv")

def podium_finishes(col):
    finishes = 0
    for k in col:
        if k <= 3:
            finishes += 1
    return finishes

df_agg = df_results.groupby(by="driverId").agg(avg_points = ("points", "mean"),
                                      podium_finishes = ("positionOrder", podium_finishes))

df_results = pd.merge(left = df_results, right = df_agg, on = "driverId", how = "left")

df_results

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,avg_points,podium_finishes
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616.0,39,2,1:27.452,218.300,1,14.313953,188
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094.0,41,3,1:27.739,217.586,1,1.407609,13
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779.0,41,5,1:28.090,216.719,1,7.740291,57
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797.0,58,7,1:28.603,215.464,1,5.790831,98
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630.0,43,1,1:27.418,218.385,1,0.937500,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25655,25661,1086,825,210,20,13,16,16,16,0.0,69,\N,NaN,37,15,1:23.511,188.856,11,1.330827,1
25656,25662,1086,848,3,23,17,17,17,17,0.0,69,\N,NaN,43,12,1:23.047,189.911,11,3.921569,2
25657,25663,1086,849,3,6,19,18,18,18,0.0,69,\N,NaN,60,8,1:22.478,191.221,11,0.134615,0
25658,25664,1086,852,213,22,16,19,19,19,0.0,68,\N,NaN,58,16,1:23.538,188.795,12,1.228571,0
25659,25665,1086,822,51,77,8,20,20,20,0.0,65,\N,NaN,60,19,1:24.002,187.752,131,9.244792,67

In [11]:
# SOLUTION 2

df_results = pd.read_csv("quiz_data/results_cleaned.csv")

def podium_finishes(col):
    return (col <= 3).sum()

df_agg = df_results.groupby(by="driverId").agg(avg_points = ("points", "mean"),
                                      podium_finishes = ("positionOrder", podium_finishes))

df_results = pd.merge(left = df_results, right = df_agg, on = "driverId", how = "left")

df_results

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,avg_points,podium_finishes
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616.0,39,2,1:27.452,218.300,1,14.313953,188
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094.0,41,3,1:27.739,217.586,1,1.407609,13
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779.0,41,5,1:28.090,216.719,1,7.740291,57
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797.0,58,7,1:28.603,215.464,1,5.790831,98
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630.0,43,1,1:27.418,218.385,1,0.937500,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25655,25661,1086,825,210,20,13,16,16,16,0.0,69,\N,NaN,37,15,1:23.511,188.856,11,1.330827,1
25656,25662,1086,848,3,23,17,17,17,17,0.0,69,\N,NaN,43,12,1:23.047,189.911,11,3.921569,2
25657,25663,1086,849,3,6,19,18,18,18,0.0,69,\N,NaN,60,8,1:22.478,191.221,11,0.134615,0
25658,25664,1086,852,213,22,16,19,19,19,0.0,68,\N,NaN,58,16,1:23.538,188.795,12,1.228571,0
25659,25665,1086,822,51,77,8,20,20,20,0.0,65,\N,NaN,60,19,1:24.002,187.752,131,9.244792,67